apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativitiesbooks
spec:
  selector:
    matchLabels:
      app: nativitiesbooks
  replicas: 1 
  template: 
    metadata:
      labels:
        app: nativitiesbooks
    spec:
      containers:
      - name: rpnweb
        image: phx.ocir.io/idn2y0witocj/nativitiesbooks:inicial
        ports:
        - containerPort: 3009
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
 name: backend-service
spec:
 type: NodePort
 selector:
   app: nativitiesbooks
 ports:
   - name: client
     protocol: TCP
     port: 3009
     nodePort: 32081
 selector:
   app: nativitiesbooks
