apiVersion: v1
kind:Pod
metadata:
   name: rnp
spec:
      containers:
      - name: rnp
    # enter the path to your image, be sure to include the correct region prefix    
        image: phx.ocir.io/idn2y0witocj/project01/rnpweb:inicial
        ports:
        - containerPort: 80
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
