apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: RNP
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: RNP
    spec:
      containers:
      - name: rnpweb
        image: rnpweb:inicial
        ports:
        - containerPort: 8009
