apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpnweb
spec:
  selector:
    matchLabels:
      app: rpnweb
  replicas: 1 
  template: 
    metadata:
      labels:
        app: rpnweb
    spec:
      containers:
      - name: rpnweb
        image: phx.ocir.io/idn2y0witocj/project01/rnpweb:inicial
        ports:
        - containerPort: 8009
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
